version: "3"

networks:
  notes:
    external:
      name: notes-app

services: 
   app:
      container_name: notesapp
      image: notesapp
      hostname: notesapp
      networks:
        - notes
      build:
         context: .
         dockerfile: Dockerfile
      depends_on:
         - postgres
      expose:
         - 5000
      ports:
         - '0.0.0.0:5000:5000'
      environment:
         -  DB_HOST=notesapp-db
         -  DB_PORT=5432
         -  DB_NAME=notes
         -  DB_USERNAME=demo
         -  DB_PASSWORD=secure_password
         -  FLASK_ENV=development
         -  FLASK_APP=.
    
   postgres:
      image: postgres:latest
      hostname: notesapp-db
      restart: always
      networks:
        - notes
      environment:
         - POSTGRES_USER=demo
         - POSTGRES_PASSWORD=secure_password
         - POSTGRES_DB=notes
      expose:
         - 5432
      volumes:
         - ./postgres-data:/var/lib/postgresql/data
         - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
